green_api:
  instance_id: "your-instance-id"
  token: "your-token"

routes:
  "1234567890@c.us":
    - "https://n8n.local/webhook/one"
    - "https://n8n.local/webhook/two"
  "0987654321@c.us":
    - "https://n8n.local/webhook/three"
